gsap.registerPlugin(ScrollTrigger);
const load=gsap.timeline();load.to('.loader-line i',{width:'100%',duration:.8,ease:'power2.inOut'}).to('.loader-mark',{y:-20,opacity:0,duration:.45,ease:'power2.in'},'+=.1').to('.loader>span,.loader-line',{opacity:0,duration:.25},'<').to('.loader',{yPercent:-100,duration:.85,ease:'power4.inOut'}).from('.hero h1 b',{yPercent:115,stagger:.12,duration:1.15,ease:'power4.out'},'-=.25').from('.hero-kicker,.hero-bottom',{opacity:0,y:20,stagger:.08,duration:.7},'-=.65');
gsap.to('.progress i',{scaleX:1,ease:'none',scrollTrigger:{trigger:'body',start:'top top',end:'bottom bottom',scrub:.15}});
if(matchMedia('(pointer:fine)').matches){const c=document.querySelector('.cursor');let mx=innerWidth/2,my=innerHeight/2,cx=mx,cy=my;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY});gsap.ticker.add(()=>{cx+=(mx-cx)*.18;cy+=(my-cy)*.18;gsap.set(c,{x:cx,y:cy})});document.querySelectorAll('a,.work,button').forEach(el=>{el.addEventListener('mouseenter',()=>gsap.to(c,{scale:1.8,duration:.25}));el.addEventListener('mouseleave',()=>gsap.to(c,{scale:1,duration:.25}))})}
const hero=gsap.timeline({scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom bottom',scrub:1}});hero.to('.hero h1',{scale:.58,y:-100,opacity:.12,ease:'none'},0).to('.glow-one',{scale:2.15,x:'-30vw',y:'20vh',rotation:80,ease:'none'},0).to('.glow-two',{scale:3.2,x:'30vw',y:'-20vh',ease:'none'},0).to('.hero-kicker,.hero-bottom',{opacity:0,ease:'none'},.1);
gsap.from('.statement h2',{y:120,opacity:0,duration:1.2,ease:'power4.out',scrollTrigger:{trigger:'.statement h2',start:'top 82%'}});gsap.to('.asterisk',{rotation:240,ease:'none',scrollTrigger:{trigger:'.statement',start:'top bottom',end:'bottom top',scrub:1}});gsap.from('.statement p',{x:100,opacity:0,duration:1,scrollTrigger:{trigger:'.statement p',start:'top 85%'}});
const lens=gsap.timeline({scrollTrigger:{trigger:'.lens',start:'top top',end:'bottom bottom',scrub:1}});lens.to('.lens-window',{width:'115vw',height:'115vw',borderRadius:'0%',ease:'power2.inOut'},0).to('.planet',{scale:1.8,x:'-12vw',y:'15vh',rotation:35,ease:'none'},0).fromTo('.world-type',{scale:.35,opacity:0},{scale:1.15,opacity:1,ease:'none'},.05).to('.world-grid',{rotation:8,scale:2.1,ease:'none'},0).to('.lens-label',{opacity:0},.15).to('.orbit-copy',{opacity:1,y:20},.5).to('.world-type',{x:'22vw'},.55);
gsap.to('.ticker div',{xPercent:-42,ease:'none',scrollTrigger:{trigger:'.ticker',start:'top bottom',end:'bottom top',scrub:1}});
const track=document.querySelector('.track');const distance=()=>Math.max(0,track.scrollWidth-innerWidth+innerWidth*.05);gsap.to(track,{x:()=>-distance(),ease:'none',scrollTrigger:{trigger:'.works',start:'top top',end:'bottom bottom',scrub:.75,invalidateOnRefresh:true}});document.querySelectorAll('.work').forEach((card,i)=>gsap.from(card,{y:i%2?80:150,rotation:i%2?2:-2,ease:'none',scrollTrigger:{trigger:'.works',start:'top 70%',end:'top 10%',scrub:1}}));
const focus=gsap.timeline({scrollTrigger:{trigger:'.career-focus',start:'top top',end:'bottom bottom',scrub:1}});focus.fromTo('.career-focus h2',{scale:.5,x:'30vw'},{scale:1.05,x:'-8vw',ease:'none'},0).to('.radar',{scale:1.8,x:'-25vw',rotation:300,ease:'none'},0).fromTo('.focus-copy',{opacity:0,y:80},{opacity:1,y:0,ease:'none'},.45).to('.career-focus h2',{opacity:.2},.72);
gsap.from('.route>div',{y:80,opacity:0,stagger:.15,duration:.8,ease:'power3.out',scrollTrigger:{trigger:'.route',start:'top 80%'}});
gsap.from('.directions-head h2',{y:100,opacity:0,duration:1,ease:'power4.out',scrollTrigger:{trigger:'.directions-head',start:'top 75%'}});
const careerData={creative:{title:'CREATIVE & MEDIA',text:'Explore design, animation, content, photography, film, advertising and other careers where ideas become experiences.'},tech:{title:'TECHNOLOGY & DIGITAL',text:'Explore software, AI, cybersecurity, data and digital product careers where curiosity meets problem-solving.'},people:{title:'HEALTH & PEOPLE',text:'Explore healthcare, education, social service, coaching and other careers centred on helping people grow and thrive.'},engineering:{title:'ENGINEERING & MAKING',text:'Explore engineering, robotics, aviation, built environment and technical careers that turn ideas into working systems.'},business:{title:'BUSINESS & LEADERSHIP',text:'Explore entrepreneurship, marketing, finance, operations and people-focused careers that organise ideas and move them forward.'}};
const selected=new Set();document.querySelectorAll('.choices button').forEach(btn=>btn.addEventListener('click',()=>{btn.classList.toggle('active');const key=btn.dataset.world;if(btn.classList.contains('active'))selected.add(key);else selected.delete(key);const result=document.querySelector('.result');if(!selected.size){result.querySelector('h3').innerHTML='CHOOSE WHAT<br>SPARKS YOUR CURIOSITY.';result.querySelector('p').textContent='Select an interest above. We’ll surface career worlds worth exploring.';return}const items=[...selected].map(k=>careerData[k]);result.querySelector('h3').innerHTML=items.map(x=>x.title).join(' +<br>');result.querySelector('p').textContent=items.map(x=>x.text).join(' ');gsap.fromTo(result,{y:20,opacity:.5},{y:0,opacity:1,duration:.45})}));
gsap.from('.contact h2',{y:130,opacity:0,duration:1.3,ease:'power4.out',scrollTrigger:{trigger:'.contact',start:'top 60%'}});const magnetic=document.querySelector('.magnetic');if(magnetic&&matchMedia('(pointer:fine)').matches){magnetic.addEventListener('mousemove',e=>{const r=magnetic.getBoundingClientRect();gsap.to(magnetic,{x:(e.clientX-r.left-r.width/2)*.28,y:(e.clientY-r.top-r.height/2)*.28,duration:.3})});magnetic.addEventListener('mouseleave',()=>gsap.to(magnetic,{x:0,y:0,duration:.6,ease:'elastic.out(1,.4)'}))}addEventListener('resize',()=>ScrollTrigger.refresh());